/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as MandatoRouteImport } from './routes/mandato'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BiografiaRouteImport } from './routes/biografia'
import { Route as BairrosRouteImport } from './routes/bairros'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosSlugRouteImport } from './routes/projetos.$slug'

const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const MandatoRoute = MandatoRouteImport.update({
  id: '/mandato',
  path: '/mandato',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BiografiaRoute = BiografiaRouteImport.update({
  id: '/biografia',
  path: '/biografia',
  getParentRoute: () => rootRouteImport,
} as any)
const BairrosRoute = BairrosRouteImport.update({
  id: '/bairros',
  path: '/bairros',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosSlugRoute = ProjetosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjetosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/bairros': typeof BairrosRoute
  '/biografia': typeof BiografiaRoute
  '/contato': typeof ContatoRoute
  '/mandato': typeof MandatoRoute
  '/noticias': typeof NoticiasRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/projetos/$slug': typeof ProjetosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/bairros': typeof BairrosRoute
  '/biografia': typeof BiografiaRoute
  '/contato': typeof ContatoRoute
  '/mandato': typeof MandatoRoute
  '/noticias': typeof NoticiasRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/projetos/$slug': typeof ProjetosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/bairros': typeof BairrosRoute
  '/biografia': typeof BiografiaRoute
  '/contato': typeof ContatoRoute
  '/mandato': typeof MandatoRoute
  '/noticias': typeof NoticiasRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/projetos/$slug': typeof ProjetosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/bairros'
    | '/biografia'
    | '/contato'
    | '/mandato'
    | '/noticias'
    | '/projetos'
    | '/projetos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/bairros'
    | '/biografia'
    | '/contato'
    | '/mandato'
    | '/noticias'
    | '/projetos'
    | '/projetos/$slug'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/bairros'
    | '/biografia'
    | '/contato'
    | '/mandato'
    | '/noticias'
    | '/projetos'
    | '/projetos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  BairrosRoute: typeof BairrosRoute
  BiografiaRoute: typeof BiografiaRoute
  ContatoRoute: typeof ContatoRoute
  MandatoRoute: typeof MandatoRoute
  NoticiasRoute: typeof NoticiasRoute
  ProjetosRoute: typeof ProjetosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mandato': {
      id: '/mandato'
      path: '/mandato'
      fullPath: '/mandato'
      preLoaderRoute: typeof MandatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biografia': {
      id: '/biografia'
      path: '/biografia'
      fullPath: '/biografia'
      preLoaderRoute: typeof BiografiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bairros': {
      id: '/bairros'
      path: '/bairros'
      fullPath: '/bairros'
      preLoaderRoute: typeof BairrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$slug': {
      id: '/projetos/$slug'
      path: '/$slug'
      fullPath: '/projetos/$slug'
      preLoaderRoute: typeof ProjetosSlugRouteImport
      parentRoute: typeof ProjetosRoute
    }
  }
}

interface ProjetosRouteChildren {
  ProjetosSlugRoute: typeof ProjetosSlugRoute
}

const ProjetosRouteChildren: ProjetosRouteChildren = {
  ProjetosSlugRoute: ProjetosSlugRoute,
}

const ProjetosRouteWithChildren = ProjetosRoute._addFileChildren(
  ProjetosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  BairrosRoute: BairrosRoute,
  BiografiaRoute: BiografiaRoute,
  ContatoRoute: ContatoRoute,
  MandatoRoute: MandatoRoute,
  NoticiasRoute: NoticiasRoute,
  ProjetosRoute: ProjetosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
